### ISSUE TITLE
unable to load

### ISSUE THREAD

**Issue by johmicd** [paolotremadio/homebridge-automation-bluetooth-presence#17]
I get the following in the log:

[4/7/2022, 5:57:10 PM] The plugin "homebridge-automation-bluetooth-presence" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!
[4/7/2022, 5:57:10 PM] ====================
[4/7/2022, 5:57:10 PM] ERROR LOADING PLUGIN homebridge-automation-bluetooth-presence:
[4/7/2022, 5:57:10 PM] Error: Cannot find module 'xpc-connection'
Require stack:
- /opt/homebrew/lib/node_modules/homebridge-automation-bluetooth-presence/node_modules/noble/lib/mac/highsierra.js
- /opt/homebrew/lib/node_modules/homebridge-automation-bluetooth-presence/node_modules/noble/lib/mac/bindings.js
- /opt/homebrew/lib/node_modules/homebridge-automation-bluetooth-presence/node_modules/noble/lib/resolve-bindings.js
- /opt/homebrew/lib/node_modules/homebridge-automation-bluetooth-presence/node_modules/noble/index.js
- /opt/homebrew/lib/node_modules/homebridge-automation-bluetooth-presence/index.js
- /opt/homebrew/lib/node_modules/homebridge/lib/plugin.js
- /opt/homebrew/lib/node_modules/homebridge/lib/pluginManager.js
- /opt/homebrew/lib/node_modules/homebridge/lib/server.js
- /opt/homebrew/lib/node_modules/homebridge/lib/cli.js
- /opt/homebrew/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/homebridge-automation-bluetooth-presence/node_modules/noble/lib/mac/highsierra.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)

**Comment by paolotremadio** [comment]
What hardware are you running on and what’s your version of node?
